### ISSUE TITLE
Right Click

### ISSUE THREAD

**Issue by msimsjr** [MillersvilleCS/pumlbuilder#70]
Right click shouldn't create things. It should have a context menu.

**Comment by msimsjr** [comment]
Also doing the same thing when doing middle mouse-click.

**Comment by jwakefield21** [comment]
Currently you can only create objects on left click and I have a basic context menu appearing when you right click instead of it creating objects. The middle mouse button does not do anything at the current time. Looking a way to get context menu to disappear when you right or left click somewhere else, context menu will close when a selection is made or esc is pressed. Still needs pushed though.
